/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef EXAMPLE_Example_Interface_DBUS_STUB_ADAPTER_HPP_
#define EXAMPLE_Example_Interface_DBUS_STUB_ADAPTER_HPP_

#include <example/ExampleInterfaceStub.hpp>
#include "example/ExampleInterfaceDBusDeployment.hpp"        

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace example {

typedef CommonAPI::DBus::DBusStubAdapterHelper<ExampleInterfaceStub> ExampleInterfaceDBusStubAdapterHelper;

class ExampleInterfaceDBusStubAdapterInternal
    : public virtual ExampleInterfaceStubAdapter,
      public ExampleInterfaceDBusStubAdapterHelper
{
public:
    ExampleInterfaceDBusStubAdapterInternal(
            const CommonAPI::DBus::DBusAddress &_address,
            const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
            const std::shared_ptr<CommonAPI::StubBase> &_stub);

    ~ExampleInterfaceDBusStubAdapterInternal();

    virtual const bool hasFreedesktopProperties();




    const ExampleInterfaceDBusStubAdapterHelper::StubDispatcherTable& getStubDispatcherTable();
    const CommonAPI::DBus::StubAttributeTable& getStubAttributeTable();

    void deactivateManagedInstances();
    

static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::example::ExampleInterfaceStub,
        CommonAPI::Version
        > getExampleInterfaceInterfaceVersionStubDispatcher;




static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::example::ExampleInterfaceStub,
    std::tuple<>,
    std::tuple<>,
    std::tuple<>,
    std::tuple<>
    
    > playStubDispatcher;

static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::example::ExampleInterfaceStub,
    std::tuple<int64_t, int64_t>,
    std::tuple<int64_t, int64_t>,
    std::tuple<CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>,
    std::tuple<CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>
    
    > add2StubDispatcher;




 protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const;

 private:
    ExampleInterfaceDBusStubAdapterHelper::StubDispatcherTable stubDispatcherTable_;
    CommonAPI::DBus::StubAttributeTable stubAttributeTable_;
};

class ExampleInterfaceDBusStubAdapter
    : public ExampleInterfaceDBusStubAdapterInternal,
      public std::enable_shared_from_this<ExampleInterfaceDBusStubAdapter> {
public:
    ExampleInterfaceDBusStubAdapter(
    	const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub)
    	: CommonAPI::DBus::DBusStubAdapter(
    		_address, 
    		_connection,
            false),
          ExampleInterfaceDBusStubAdapterInternal(
          	_address, 
          	_connection, 
          	_stub) { 
    }
};

} // namespace example

#endif // EXAMPLE_Example_Interface_DBUS_STUB_ADAPTER_HPP_
