/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef EXAMPLE_Example_Interface_PROXY_HPP_
#define EXAMPLE_Example_Interface_PROXY_HPP_

#include <example/ExampleInterfaceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace example {

template <typename ... _AttributeExtensions>
class ExampleInterfaceProxy
    : virtual public ExampleInterface, 
      virtual public ExampleInterfaceProxyBase,
      public _AttributeExtensions... {
public:
    ExampleInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ExampleInterfaceProxy();

    typedef ExampleInterface InterfaceType;




    /**
     * Calls play with synchronous semantics.
     * 
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void play(CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls play with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> playAsync(PlayAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2 with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void add2(const int64_t &_left, const int64_t &_right, CommonAPI::CallStatus &_internalCallStatus, int64_t &_sum, int64_t &_diff, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2 with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> add2Async(const int64_t &_left, const int64_t &_right, Add2AsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2struct with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void add2struct(const ExampleInterface::Summands &_s, CommonAPI::CallStatus &_internalCallStatus, ExampleInterface::SumDiff &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2struct with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> add2structAsync(const ExampleInterface::Summands &_s, Add2structAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2nestedStruct with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void add2nestedStruct(const ExampleInterface::Params &_p, CommonAPI::CallStatus &_internalCallStatus, ExampleInterface::SumDiff &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2nestedStruct with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> add2nestedStructAsync(const ExampleInterface::Params &_p, Add2nestedStructAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr);


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr<ExampleInterfaceProxyBase> delegate_;
};

typedef ExampleInterfaceProxy<> ExampleInterfaceProxyDefault;


//
// ExampleInterfaceProxy Implementation
//
template <typename ... _AttributeExtensions>
ExampleInterfaceProxy<_AttributeExtensions...>::ExampleInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast<ExampleInterfaceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast<ExampleInterfaceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ExampleInterfaceProxy<_AttributeExtensions...>::~ExampleInterfaceProxy() {
}

template <typename ... _AttributeExtensions>
void ExampleInterfaceProxy<_AttributeExtensions...>::play(CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->play(_internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ExampleInterfaceProxy<_AttributeExtensions...>::playAsync(PlayAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->playAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void ExampleInterfaceProxy<_AttributeExtensions...>::add2(const int64_t &_left, const int64_t &_right, CommonAPI::CallStatus &_internalCallStatus, int64_t &_sum, int64_t &_diff, const CommonAPI::CallInfo *_info) {
    delegate_->add2(_left, _right, _internalCallStatus, _sum, _diff, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ExampleInterfaceProxy<_AttributeExtensions...>::add2Async(const int64_t &_left, const int64_t &_right, Add2AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->add2Async(_left, _right, _callback, _info);
}
template <typename ... _AttributeExtensions>
void ExampleInterfaceProxy<_AttributeExtensions...>::add2struct(const ExampleInterface::Summands &_s, CommonAPI::CallStatus &_internalCallStatus, ExampleInterface::SumDiff &_result, const CommonAPI::CallInfo *_info) {
    delegate_->add2struct(_s, _internalCallStatus, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ExampleInterfaceProxy<_AttributeExtensions...>::add2structAsync(const ExampleInterface::Summands &_s, Add2structAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->add2structAsync(_s, _callback, _info);
}
template <typename ... _AttributeExtensions>
void ExampleInterfaceProxy<_AttributeExtensions...>::add2nestedStruct(const ExampleInterface::Params &_p, CommonAPI::CallStatus &_internalCallStatus, ExampleInterface::SumDiff &_result, const CommonAPI::CallInfo *_info) {
    delegate_->add2nestedStruct(_p, _internalCallStatus, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ExampleInterfaceProxy<_AttributeExtensions...>::add2nestedStructAsync(const ExampleInterface::Params &_p, Add2nestedStructAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->add2nestedStructAsync(_p, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ExampleInterfaceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ExampleInterfaceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ExampleInterfaceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ExampleInterfaceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ExampleInterfaceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace example


#endif // EXAMPLE_Example_Interface_PROXY_HPP_
